// <auto-generated />
namespace WebAPI_Learning_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_FixDates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_FixDates));
        
        string IMigrationMetadata.Id
        {
            get { return "201601301643584_User_FixDates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
